### ISSUE TITLE
Home screen for Steam user to sign in

### ISSUE THREAD

**Issue by richardbreslin** [WSU-4110/westeam#1]
|FR1.  Customers  Greetings UI|
|---||**Goal**: Have a button to login with STEAM account **Stakeholders:** Steam Users|| **Description:** Display a button in the top right that says, “login with steam.” User clicks on button then is redirected to the steam login page to login for authentication. || **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|| **Version:** 1.0  ||**Date:** 09/28/2019|  **Priority:** 1 |

**Comment by mohammedali101** [comment]
We changed the "login with steam" feature and instead are going to have the Steam user enter his or her Steam ID, which will then lead them to the friends page.
