### ISSUE TITLE
FR10: Have an option for Wishlist games to be included 

### ISSUE THREAD

**Issue by Elyasmusa** [WSU-4110/westeam#11]
|FR10: Have an option for Wishlist games to be included |
|---|
|**Goal**: User convenience|
|**Stakeholders:** Steam Users|
| **Description:** Have an option to include games that are in the user’s (and/or friends’) Wishlist in game recommendations. This could help the user find a new game they are both interested in to buy and then play together.   |
| **Origin:** Based on the initial project specification document, team members produced this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2021|  
|**Priority:** 1 |

**Comment by mkorte13** [comment]
This functionality has not been implemented due to time constraints.
