### ISSUE TITLE
FR11: Click on game in list to redirect to steam store 

### ISSUE THREAD

**Issue by Elyasmusa** [WSU-4110/westeam#12]
|FR11: Click on game in list to redirect to steam store  |
|---|
|**Goal**: Easy access to view additional information about or purchase recommended game|
|**Stakeholders:** Steam Users|
| **Description:** Allow users to click on game in list to be redirected to the specified game’s Steam Store page. This will allow the user to view additional information about the game, and purchase it if they do not own it |
| **Origin:** Based on the initial project specification document, team members produced this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2021|  
|**Priority:** 1 |

**Comment by mkorte13** [comment]
This functionality was added. Clicking on the game on the output page redirects the user to the game's Steam store page.
