### ISSUE TITLE
FR12: Display list of lesser-known alternative steam titles 

### ISSUE THREAD

**Issue by Elyasmusa** [WSU-4110/westeam#13]
|FR12: Display list of lesser-known alternative steam titles  |
|---|
|**Goal**: Help users find games they may otherwise have heard of|
|**Stakeholders:** Steam Users|
| **Description:**  Display an alternative list of lesser-known games that loosely fit the user's recommendation inputs. |
| **Origin:** Based on the initial project specification document, team members produced this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2021|  
|**Priority:** 1 |

**Comment by mkorte13** [comment]
The approach of recommending unowned games was abandoned due to time restraints.

**Comment by mkorte13** [comment]
This was based of previous concept of using machine learning to recommend new games, which was changed in favor of find common games amongst multiple users.
