### ISSUE TITLE
FR14: Public chat room 

### ISSUE THREAD

**Issue by Elyasmusa** [WSU-4110/westeam#15]
|FR14: Public chat room |
|---|
|**Goal**: Community involvement|
|**Stakeholders:** Steam Users|
| **Description:** Display the WeSteam public chat room on the side of the page to be able to use for chatting with other WeSteam users and discuss video game related topics |
| **Origin:** Based on the initial project specification document, team members produced this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2021|  
|**Priority:** 1 |

**Comment by mohammedali101** [comment]
A chat box was successfully added for Steam users to socialize with their friends and others on the webpage.
