### ISSUE TITLE
FR15: Have an option to include games that you own but your friends do not own, and vice versa 

### ISSUE THREAD

**Issue by Elyasmusa** [WSU-4110/westeam#16]
|FR15: Have an option to include games that you own but your friends do not own, and vice versa |
|---|
|**Goal**: Present the different games that a user and their friends have access to|
|**Stakeholders:** Steam Users|
| **Description:** Have an option to include games that some of the users own to be included in the recommendation list. Allow the user to input the number of total Steam users in the recommendation need to own the game for it to show up (i.e., 3 out of 5, 2 out of 4, etc.) .|
| **Version:** 1.0  |
|**Date:** 09/28/2021|  
|**Priority:** 1 |

**Comment by mkorte13** [comment]
We were not able to add in this functionality due to time constraints.
