### ISSUE TITLE
FR16: Have it be in night mode, add day mode option 

### ISSUE THREAD

**Issue by Elyasmusa** [WSU-4110/westeam#17]
|FR16: Have it be in night mode, add day mode option  |
|---|
|**Goal**: All users to have control over UI color pallet|
|**Stakeholders:** Steam Users|
| **Description:** By default, have the webpage be displayed with a dark color pallet (much like Steam). But also allow the user to change it to something lighter if they choose.|
| **Version:** 1.0  |
|**Date:** 09/28/2021|  
|**Priority:** 1 |

**Comment by mohammedali101** [comment]
We could not figure out how to display the themes, thus we had to improvise this issue.
