### ISSUE TITLE
NR2: (privacy) only takes information from games owned/on Wishlist, and friends list. No other information needs to be collected

### ISSUE THREAD

**Issue by Elyasmusa** [WSU-4110/westeam#19]
|NR2: (privacy) only takes information from games owned/on Wishlist, and friends list. No other information needs to be collected |
|---|
|**Goal:** Minimize the amount of info taken from user account|
|**Stakeholders:** Steam Users|
| **Description:** Make sure we only take the minimal amount of account information needed for the website to work. This means game library, friends list, wish list, and game play data (such as hours played and achievements) |
| **Origin:** Based on the initial project specification document, team members produced this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2021|  
|**Priority:** 1 |

**Comment by mkorte13** [comment]
This requirement has been met. Info about friends list is only taken from the initially entered SteamID, and game info is only fetched for the SteamIDs entered. Additionally, Steam only allows us access to this info if the user sets their account to "public."
