### ISSUE TITLE
FR1:  Clean Home screen UI

### ISSUE THREAD

**Issue by richardbreslin** [WSU-4110/westeam#2]
|FR1:  Clean Home screen UI|
|---|
|**Goal:** Have a Clean Home Screen UI for easy navigation through the website 
**Stakeholders:** Steam Users|
| **Description:**  Have the Home Screen of the website look neat and clean to allow easier navigation and use of the website. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/28/2021  
|  **Priority:** 1 |

**Comment by mohammedali101** [comment]
The westeam Home page is easy to access and adjust to for all Steam users. Everyone who contributed made sure to make the page look clean and neat and we are satisfied with our results.
