### ISSUE TITLE
NR3: (usability) Design a user interface that the team feels is simple and easy to use. 

### ISSUE THREAD

**Issue by Elyasmusa** [WSU-4110/westeam#20]
|NR3: (usability) Design a user interface that the team feels is simple and easy to use.  |
|---|
|**Goal:** Ensure the end-user understands the website, and finds it friendly to use|
|**Stakeholders:** Steam Users|
| **Description:** The user interface should feel simple, and easy to use. There should be little to no information that is not directly relevant to the website functionality displayed on screen. Moreover, have the design resemble Steam to aid in user familiarity.  |
| **Origin:** Based on the initial project specification document, team members produced this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2021|  
|**Priority:** 1 |

**Comment by mohammedali101** [comment]
The user should be able to familiarize how westeam works once they try it out for the first time. We made sure that it was easy to grasp for everyone to try out.
