### ISSUE TITLE
NR5: (Availability): Website should be operational 95% of the time 

### ISSUE THREAD

**Issue by Elyasmusa** [WSU-4110/westeam#22]
|NR5: (Availability): Website should be operational 95% of the time  |
|---|
|**Goal:** Make sure the website is functional and operational to users|
|**Stakeholders:** Steam Users|
| **Description:** Make sure the website is usually up and running but keeps our expectations realistic. |
| **Origin:** Based on the initial project specification document, team members produced this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2021|  
|**Priority:** 1 |

**Comment by mohammedali101** [comment]
Our expectations were fulfilled and we were able to make a webpage that executes perfectly and is usable for fans of Steam.
