### ISSUE TITLE
FR2: Ability to login to Steam

### ISSUE THREAD

**Issue by richardbreslin** [WSU-4110/westeam#3]
|FR2:  Ability to login to Steam|
|---|
|**Goal:** Display button to allow users to sign in with Steam.
**Stakeholders:** Steam Users|
| **Description:** Have a text box to enter users Steam login (and potentially a second box to enter password if necessary), in addition to a button to submit the entered information to log in |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/28/2021  
|  **Priority:** 1 |

**Comment by mohammedali101** [comment]
User can login to their Steam account successfully as long as it is 17 digits and does not have a variable that is string or char.
