### ISSUE TITLE
FR3: Display friends list panel from steam login data

### ISSUE THREAD

**Issue by Elyasmusa** [WSU-4110/westeam#4]
|FR3: Display friends list panel from steam login data  |
|---|
|**Goal**: Allow users to see friends to add to recommendation output|
|**Stakeholders:** Steam Users|
|**Description:** Get the friends list of the logged in user and display the friends with their profile picture on the friend's pane. This will allow the user to quickly and easily add friends to game recommendation. |
| **Origin:** Based on the initial project specification document, team members produced this description during the first meeting.|
|**Version:** 1.0  |
|**Date:** 09/28/2021| 
|**Priority:** 1 |

**Comment by mohammedali101** [comment]
Steam users can get access to their friends list once they enter the credentials on the Home page.
