### ISSUE TITLE
BUG: Chat Does Not Update Dynamically

### ISSUE THREAD

**Issue by mkorte13** [WSU-4110/westeam#41]
Chat box only updates when user enters message, not when a different user sends one.

**Comment by Elyasmusa** [comment]
Tried my best to make it Dynamic but with my skill was not able to

**Comment by richardbreslin** [comment]
Have it partially fixed not too sure will consult documentation first.

**Comment by mohammedali101** [comment]
Chat box works fine but there are some issues that are not solved.
