### ISSUE TITLE
FR4: Have a check box that adds a specified friend to submission form 

### ISSUE THREAD

**Issue by Elyasmusa** [WSU-4110/westeam#5]
|FR4: Have a check box that adds a specified friend to submission form|
|---|
|**Goal**: Display a checkbox that adds the corresponding user to the recommendation |
|**Stakeholders:** Steam Users|
|**Description:** Next to each friend display a checkbox to select specific friends to be added to the recommendation.|
| **Origin:** Based on the initial project specification document, team members produced this description during the first meeting.|
|**Version:** 1.0  |
|**Date:** 09/28/2021| 
|**Priority:** 1 |

**Comment by mohammedali101** [comment]
The check box allows the user to select any friend he or she wishes to play with.
