### ISSUE TITLE
FR5: Keyword entry form for game preferences 

### ISSUE THREAD

**Issue by Elyasmusa** [WSU-4110/westeam#6]
|FR5: Keyword entry form for game preferences |
|---|
|**Goal**: Tailored recommendations based on genre or keywords|
|**Stakeholders:** Steam Users|
| **Description:** At some point before giving actual game recommendations, allow users to select Steam keywords (such as first-person shooter, MMO, etc.) to narrow down the output list. This should not be a necessary step. |
| **Origin:** Based on the initial project specification document, team members produced this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2021|  
|**Priority:** 1 |

**Comment by mkorte13** [comment]
We were unable to find an effective way to add this functionality. Steam API did not seem to have a way to for us to gather tag information.
