### ISSUE TITLE
FR6: Get a valid list of owned games to play with friends 

### ISSUE THREAD

**Issue by Elyasmusa** [WSU-4110/westeam#7]
|FR6: Get a valid list of owned games to play with friends|
|---|
|**Goal**:  Make sure user gets a list of games to play with friends|
|**Stakeholders:** Steam Users|
| **Description:** Take all the information entered prior (such as keywords, user & friends’ game libraries) to output a valid list of games for the user and their friends to play together. |
| **Origin:** Based on the initial project specification document, team members produced this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2021|  
|**Priority:** 1 |

**Comment by mkorte13** [comment]
While we were unable to add in functionality to narrow down the game results, we can still output a list of games that all entered Steam accounts own.
