### ISSUE TITLE
FR8: Have an option to exclude specific games

### ISSUE THREAD

**Issue by Elyasmusa** [WSU-4110/westeam#9]
|FR8: Have an option to exclude specific games|
|---|
|**Goal**: Assist recommendations by taking out user specific games.|
|**Stakeholders:** Steam Users|
| **Description:** Have an option to select games from the user's library that they do not want to have appear in the recommendations output  |
| **Origin:** Based on the initial project specification document, team members produced this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 09/28/2021|  
|**Priority:** 1 |

**Comment by mkorte13** [comment]
This functionality was dropped.
